# Site settings
author: korey ko.
title: 
header-img: img/home-bg.png
email: koreykendrick1@gmail.com
copyright_name: korey ko.
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  learncbrainy-loop8787

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
